// <auto-generated />
namespace ToDoList.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class w : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(w));
        
        string IMigrationMetadata.Id
        {
            get { return "201506032217335_w"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
